version: 1.0.{build}
image: Visual Studio 2015
before_build:
- ps: $env:path -split ";" | findstr /psi "nunit"
- set path=C:\Tools\NUnit3;%path%
- ps: $env:path -split ";" | findstr /psi "nunit"
build_script:
- cmd: PowerShell -Version 2.0 .\build.ps1
test: off
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
